In [1]:
import pandas as pd

In [9]:
forest_path = './clean_data/forest.csv'
forest_df = pd.read_csv(forest_path)
forest_df.iloc[:, 8:32]

,tc_loss_ha_2001,tc_loss_ha_2002,tc_loss_ha_2003,tc_loss_ha_2004,tc_loss_ha_2005,tc_loss_ha_2006,tc_loss_ha_2007,tc_loss_ha_2008,tc_loss_ha_2009,tc_loss_ha_2010,...,tc_loss_ha_2014,tc_loss_ha_2015,tc_loss_ha_2016,tc_loss_ha_2017,tc_loss_ha_2018,tc_loss_ha_2019,tc_loss_ha_2020,tc_loss_ha_2021,tc_loss_ha_2022,tc_loss_ha_2023
0,23,80,24,13,37,12,46,14,39,20,...,40,5,17,6,8,11,31,16,21,31
1,122,129,47,39,111,22,88,44,64,48,...,12,1,24,6,54,34,94,69,94,86
2,100,122,86,10,28,9,7,15,27,8,...,0,0,0,0,0,0,0,0,0,0
3,39,8,4,2,8,28,7,18,2,2,...,0,0,0,0,0,0,0,1,0,1
4,148,313,148,19,93,47,80,113,121,36,...,44,10,197,96,91,7,139,35,52,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,186,138,41,36,122,103,44,131,122,146,...,24,16,23,33,52,67,127,118,192,53
133,49,95,6,9,27,11,48,15,26,1,...,0,0,0,0,0,0,0,0,0,0
134,84,476,58,69,113,60,75,63,103,25,...,6,4,6,4,6,4,20,8,12,13
135,424,706,105,156,272,245,113,120,258,139,...,9,1,5,7,12,10,10,11,12,5
136,479,1079,225,366,625,177,646,95,716,74,...,32,29,19,20,38,17,23,9,20,25